data_init<-read.csv("household_power_consumption.txt", sep=";", header =T)
data_subset<-subset(data_init, Date=="1/2/2007" | Date=="2/2/2007")
data_subset$Timestamp<-strptime(paste(data_subset$Date, data_subset$Time) , "%d/%m/%Y %H:%M:%S")
png("plot3.png")
with(data_subset, plot(Timestamp, as.numeric(as.character(Sub_metering_1)), type="l", col = "black", xlab ="", ylab = "Global Active Power (kilowatts)"))
with(data_subset, lines(Timestamp, as.numeric(as.character(Sub_metering_2)), type="l", col = "red"))
with(data_subset, lines(Timestamp, as.numeric(as.character(Sub_metering_3)), type="l", col = "blue"))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       col=c("black", "red", "blue"), lty=1, cex=0.8)
dev.off()