data_init<-read.csv("household_power_consumption.txt", sep=";", header =T)
data_subset<-subset(data_init, Date=="1/2/2007" | Date=="2/2/2007")
data_subset$Timestamp<-strptime(paste(data_subset$Date, data_subset$Time) , "%d/%m/%Y %H:%M:%S")
png("plot2.png")
with(data_subset, plot(Timestamp, as.numeric(as.character(Global_active_power)), type='l', xlab ="", ylab = "Global Active Power (kilowatts)"))
dev.off()