data_init<-read.csv("household_power_consumption.txt", sep=";", header =T)
data_subset<-subset(data_init, Date=="1/2/2007" | Date=="2/2/2007")
data_subset$Timestamp<-strptime(paste(data_subset$Date, data_subset$Time) , "%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))
with(data_subset, plot(Timestamp, as.numeric(as.character(Global_active_power)), type='l', xlab ="", ylab = "Global Active Power"))
with(data_subset, plot(Timestamp, as.numeric(as.character(Voltage)), type='l', xlab ="datetime", ylab = "Voltage"))
with(data_subset, plot(Timestamp, as.numeric(as.character(Sub_metering_1)), type="n", col = "black", xlab ="", ylab = "Energy Sub Metering"))
with(data_subset, lines(Timestamp, as.numeric(as.character(Sub_metering_2)), col = "red"))
with(data_subset, lines(Timestamp, as.numeric(as.character(Sub_metering_3)), col = "blue"))
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       col=c("black", "red", "blue"), lty=1)
with(data_subset, plot(Timestamp, as.numeric(as.character(Global_reactive_power)), type='l', xlab ="datetime", ylab = "Global_reactive_power"))
dev.off()